project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - weekly-notes/week-01-notes.qmd
    - weekly-notes/week-02-notes.qmd
    - labs/Assignment1_NSC.qmd
    - weekly-notes/week-03-notes.qmd
    - weekly-notes/week-04-notes.qmd
    - model_script.qmd
    - lab4.qmd

website:
  title: "Nina Singh Carlsen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4
      - text: Labs
        menu:
          - href: labs/Assignment1_NSC.qmd
            text: Lab 1
          - href: model_script.qmd
            text: Midterm
          - href: lab4.qmd
            text: Lab 4

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
